spring.application.name=messageservice
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${authservice.host:127.0.0.1}:9000
server.port=8081

spring.grpc.client.default-channel.address=${userservice.host:localhost}:8083
spring.grpc.client.default-channel.secure=false

spring.datasource.url=jdbc:postgresql://${postgres.host:localhost}:5432/messages_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=${rabbitmq.host:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.messaging.exchange=messages.exchange
app.messaging.routing-key=message.published
