spring.application.name=messageservice
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:9000
server.port=8081

spring.grpc.client.default-channel.address=localhost:8083
spring.grpc.client.default-channel.secure=false
